# Deep Learning with PyTorch

This is notebook for excersises with [PyTorch](https://pytorch.ord) framework.

In [14]:
# Import modules
%matplotlib inline
%config InlineBackend.figure_format = 'retina'

import torch
import numpy as np
import matplotlib.pyplot as plt

from torch import nn
from torchvision import datasets, transforms

In [4]:
# Define activation functions
def sigmoid(x):
    """Sigmoid activation function"""
    return 1 / (1 + torch.exp(-x))

def tanh(x):
    """TanH (Hyperbolic Tangent Function) activation function"""
    return torch.tanh(x)

relu = nn.ReLU()

## Single Neuron

In [5]:
# Generate random data
torch.manual_seed(7)

# Init features, weights, bias
features = torch.randn(1, 5)
weights = torch.randn_like(features)
bias = torch.randn(1, 1)

In [6]:
print("Features: ", features)
print("Weights: ", weights)
print("Bias: ", bias)

Features:  tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
Weights:  tensor([[-0.8948, -0.3556,  1.2324,  0.1382, -1.6822]])
Bias:  tensor([[0.3177]])


In [7]:
# Calculate output
y = sigmoid(torch.sum(features * weights) + bias)
y

tensor([[0.1595]])

In [8]:
# Calculate output using matrix multiplication
y = sigmoid(torch.mm(features, weights.view(5,1)) + bias)
y

tensor([[0.1595]])

## Stack neurons to layers

In [9]:
# Define the structure
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# Bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [10]:
print("Features: ", features)
print("Input: ", features.shape[1])
print("W1: ", W1)
print("W2: ", W2)
print("B1: ", B1)
print("B2: ", B2)

Features:  tensor([[-0.1468,  0.7861,  0.9468, -1.1143,  1.6908]])
Input:  5
W1:  tensor([[0.1328, 0.1373],
        [0.2405, 1.3955],
        [1.3470, 2.4382],
        [0.2028, 2.4505],
        [2.0256, 1.7792]])
W2:  tensor([[-0.9179],
        [-0.4578]])
B1:  tensor([[-0.7245,  1.2799]])
B2:  tensor([[-0.9941]])


In [11]:
h = relu(torch.mm(features, W1) + B1)
y = sigmoid(torch.mm(h, W2) + B2)
y

tensor([[0.0011]])